export const INITIAL_CABANG = [
  {
    id: "CAB-001",
    kode: "cabang_01",
    nama: "Outlet Cabang 01",
    alamat: "Jl. Jenderal Sudirman No. 12, Tarakan",
    penanggungJawab: "Abu Arfan",
    telepon: "0812-3456-7891",
    jamOperasional: "08:00 - 22:00 WITA",
    status: "Aktif",
    jumlahStaff: 1,
    tanggalBuka: "01 Januari 2026",
    kapasitas: "500 Cup / Hari",
    fasilitas: ["Dine In", "Take Away", "QRIS Payment"],
  },
  {
    id: "CAB-002",
    kode: "cabang_02",
    nama: "Outlet Cabang 02",
    alamat: "Jl. Mulawarman No. 88, Tarakan",
    penanggungJawab: "Arief Rahman",
    telepon: "0812-3456-7892",
    jamOperasional: "08:00 - 22:00 WITA",
    status: "Aktif",
    jumlahStaff: 1,
    tanggalBuka: "15 Januari 2026",
    kapasitas: "500 Cup / Hari",
    fasilitas: ["Take Away", "Delivery", "QRIS Payment"],
  },
];
