export const INITIAL_KARYAWAN = [
  {
    id: "EMP-001",
    nik: "EST-01001",
    nama: "Abu Arfan",
    role: "Staff",
    cabang: "cabang_01",
    telepon: "0812-3456-7891",
    email: "abuarfan@estehistimewa.com",
    status: "Aktif",
    shift: "Pagi",
    tglBergabung: "01 Jan 2026",
    posisi: "Staff Outlet Cabang 01",
  },
  {
    id: "EMP-002",
    nik: "EST-02002",
    nama: "Arief Rahman",
    role: "Staff",
    cabang: "cabang_02",
    telepon: "0812-3456-7892",
    email: "arief@estehistimewa.com",
    status: "Aktif",
    shift: "Sore",
    tglBergabung: "15 Jan 2026",
    posisi: "Staff Outlet Cabang 02",
  },
];
