const APP_CONFIG = {
  // Isi dengan Spreadsheet ID yang sudah ada.
  SPREADSHEET_ID: "1xRueQWq6ObkI6erdasaM_eL56dm8WIj76Sb1ZHP-uB8",
  SHEET_NAME: "Rincian",
  HEADER_ROW: 1,
  ID_COLUMN_INDEX: 1, // kolom A
  DEFAULT_HEADERS: [
    "NO TRANSAKSI",
    "SHIFT",
    "ARUS DANA",
    "KASIR",
    "STOK AWAL GELAS",
    "GELAS MASUK",
    "GELAS LAKU",
    "GELAS RUSAK",
    "STOK AKHIR GELAS",
    "Rp 100.000",
    "Rp 75.000",
    "Rp 50.000",
    "Rp 20.000",
    "Rp 10.000",
    "Rp 5.000",
    "Rp 2.000",
    "Rp 1.000",
    "Rp 500",
    "Rp 200",
    "Rp 100",
    "TOTAL NOTA",
    "PENGELUARAN",
    "UNAG MASUK",
    "ES BATU DEPO",
    "ES BATU BELI",
    "TEH",
    "GULA",
  ],
};
